
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-supervisor-appscode-com-v1alpha1-clustermaintenancewindow
  failurePolicy: Fail
  name: mclustermaintenancewindow.kb.io
  rules:
  - apiGroups:
    - supervisor.appscode.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clustermaintenancewindows
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-supervisor-appscode-com-v1alpha1-maintenancewindow
  failurePolicy: Fail
  name: mmaintenancewindow.kb.io
  rules:
  - apiGroups:
    - supervisor.appscode.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - maintenancewindows
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-supervisor-appscode-com-v1alpha1-clustermaintenancewindow
  failurePolicy: Fail
  name: vclustermaintenancewindow.kb.io
  rules:
  - apiGroups:
    - supervisor.appscode.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clustermaintenancewindows
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-supervisor-appscode-com-v1alpha1-maintenancewindow
  failurePolicy: Fail
  name: vmaintenancewindow.kb.io
  rules:
  - apiGroups:
    - supervisor.appscode.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - maintenancewindows
  sideEffects: None
