# permissions for end users to view approvalpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: approvalpolicy-viewer-role
rules:
- apiGroups:
  - supervisor.appscode.com
  resources:
  - approvalpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - supervisor.appscode.com
  resources:
  - approvalpolicies/status
  verbs:
  - get
