# permissions for end users to edit maintenancewindows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: maintenancewindow-editor-role
rules:
- apiGroups:
  - supervisor.appscode.com
  resources:
  - maintenancewindows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - supervisor.appscode.com
  resources:
  - maintenancewindows/status
  verbs:
  - get
