# permissions for end users to view maintenancewindows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: maintenancewindow-viewer-role
rules:
- apiGroups:
  - supervisor.appscode.com
  resources:
  - maintenancewindows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - supervisor.appscode.com
  resources:
  - maintenancewindows/status
  verbs:
  - get
