# permissions for end users to edit recommendations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: recommendation-editor-role
rules:
- apiGroups:
  - supervisor.appscode.com
  resources:
  - recommendations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - supervisor.appscode.com
  resources:
  - recommendations/status
  verbs:
  - get
