# permissions for end users to view recommendations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: recommendation-viewer-role
rules:
- apiGroups:
  - supervisor.appscode.com
  resources:
  - recommendations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - supervisor.appscode.com
  resources:
  - recommendations/status
  verbs:
  - get
