
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: recommendations.supervisor.appscode.com
spec:
  group: supervisor.appscode.com
  names:
    kind: Recommendation
    listKind: RecommendationList
    plural: recommendations
    singular: recommendation
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Recommendation is the Schema for the recommendations API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: RecommendationSpec defines the desired state of Recommendation
            properties:
              approver:
                properties:
                  name:
                    type: string
                  notes:
                    type: string
                required:
                - name
                type: object
              description:
                type: string
              maintenanceWindow:
                description: TypedObjectReference represents an typed namespaced object.
                properties:
                  apiGroup:
                    type: string
                  kind:
                    type: string
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                    type: string
                  namespace:
                    description: 'Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/'
                    type: string
                required:
                - name
                type: object
              operation:
                type: object
              status:
                default: UnderReview
                enum:
                - UnderReview
                - Approved
                - Rejected
                type: string
            required:
            - operation
            type: object
          status:
            description: RecommendationStatus defines the observed state of Recommendation
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
