apiVersion: supervisor.appscode.com/v1alpha1
kind: Recommendation
metadata:
  name: upgrade-recommendation
  namespace: demo
spec:
  description: "MongoDB Database Restart"
  target:
    apiGroup: kubedb.com/v1alpha2
    kind: MongoDB
    name: mg-rs
  operation:
    apiVersion: ops.kubedb.com/v1alpha1
    kind: MongoDBOpsRequest
    metadata:
      name: mongo-restart
      namespace: demo
    spec:
      type: Restart
      databaseRef:
        name: mg-rs
  recommender:
    name: kubedb-ops-manager


